micronaut:
  application:
    name: backend
  server:
    cors:
      enabled: true
  metrics:
    enabled: true
    export:
      cloudwatch:
        enabled: false
        namespace: APP/attestation-backend
        batchSize: 10
