name: "Frontend CI"

on:
  push:
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  frontend-p1:
    uses: ./.github/workflows/frontend-p1.yml

  deploy-frontend:
    needs:
      - frontend-p1
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (
      github.ref == 'refs/heads/prod' ||
      github.ref == 'refs/heads/test')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: frontend
          path: frontend/public/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: inject env based on branch
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/prod" ]; then
            S3_BUCKET=attestation-id-frontend
            CLOUDFRONT_ID=E21GE7V99U1LOT
          else
            S3_BUCKET=attestation-id-frontend-test
            CLOUDFRONT_ID=E2OMBEMU3MTR8V
          fi
          echo "S3_BUCKET=${S3_BUCKET}" >> $GITHUB_ENV
          echo "CLOUDFRONT_ID=${CLOUDFRONT_ID}" >> $GITHUB_ENV
      - name: deploy
        run: |
          aws s3 sync frontend/public/ "s3://${S3_BUCKET}/" --cache-control 'max-age=31536000' --quiet \
          && aws s3 cp "s3://${S3_BUCKET}/index.html" "s3://${S3_BUCKET}/index.html" --cache-control 'max-age=0,s-maxage=2592000' \
          && aws s3 cp "s3://${S3_BUCKET}/build/bundle.css" "s3://${S3_BUCKET}/build/bundle.css" --cache-control 'max-age=0,s-maxage=2592000' \
          && aws s3 cp "s3://${S3_BUCKET}/build/bundle.js" "s3://${S3_BUCKET}/build/bundle.js" --cache-control 'max-age=0,s-maxage=2592000' \
          && aws cloudfront create-invalidation --distribution-id "${CLOUDFRONT_ID}" --paths '/*'
