name: "Plugin Auth0 CI"

on:
  push:
    paths:
      - "plugins/auth0-plugin/**"
  pull_request:
    paths:
      - "plugins/auth0-plugin/**"

env:
  JAVA_VER: 11

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ env.JAVA_VER }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VER }}
      - name: Build with Gradle
        run: |
          java -version
          backend/gradlew plugins:auth0-plugin:shadowjar
      - uses: actions/upload-artifact@v2
        with:
          name: auth0-plugin
          path: plugins/auth0-plugin/build/libs/auth0-plugin*.jar

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    # Only push to stage, hotfix, or main will trigger deployment
    if: github.event_name == 'push' && (
      github.ref == 'refs/heads/stage' ||
      github.ref == 'refs/heads/hotfix' ||
      github.ref == 'refs/heads/prod'
      )
    steps:
      - name: get ansible scripts
        uses: actions/checkout@v2
        with:
          repository: AlphaWallet/attestation.id-deployment
          path: "attestation.id-deployment"
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/download-artifact@v2
        with:
          name: auth0-plugin
          path: attestation.id-deployment/backend-ansible/roles/backend/files/attestation/plugins/
      - name: deploy
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          TF_WORKSPACE_ID: ${{ secrets.ATTESTATION_ID_BACKEND_WORKSPACE_ID }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          ANSIBLE_GROUP: stage
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_FORCE_COLOR: True
          ANSIBLE_PIPELINING: True
          ANSIBLE_SSH_CONTROL_PATH: /tmp/ansible-ssh-%%h-%%p-%%r
        run: |
          mv -fv attestation.id-deployment/backend-ansible/roles/backend/files/attestation/plugins/auth0-plugin*.jar \
            attestation.id-deployment/backend-ansible/roles/backend/files/attestation/plugins/auth0-plugin.jar
          tf_outputs_json="$(curl -s -H "Authorization: Bearer ${TF_API_TOKEN}" "https://app.terraform.io/api/v2/workspaces/${TF_WORKSPACE_ID}/current-state-version?include=outputs")"
          backend_ec2_public_ip="$(echo "${tf_outputs_json}" | jq -r '.included[].attributes | select(.name == "backend_ec2_public_ip").value')"
          cd attestation.id-deployment/backend-ansible/
          eval $(ssh-agent -s)
          echo "${EC2_SSH_PRIVATE_KEY}" | ssh-add -
          sed -i "/\[${ANSIBLE_GROUP}\]/ a ${backend_ec2_public_ip}" hosts
          ansible-playbook -i hosts -l "${ANSIBLE_GROUP}" site.yml
